apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-project-5-deployment
  labels:
    app: sample-project-5
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-project-5
  template:
    metadata:
      labels:
        app: sample-project-5
    spec:
      containers:
      - name: sample-project-5-container
        image: 583192906263.dkr.ecr.ap-south-1.amazonaws.com/demo:SAMPLE-PROJECT-5
        imagePullPolicy: Always
        ports:
        - name: web
            containerPort: 80
      imagePullSecrets:
          - name: regcred
